### ISSUE TITLE
PlayCore- In-App Reviews

### ISSUE THREAD

**Issue by saamerm** [PatGet/XamarinPlayCoreUpdater#2] opened 2020-08-25 20:44 UTC
Hi! Does this package support the Android "In App Reviews" feature mentioned [here](https://developer.android.com/guide/playcore/in-app-review)?

[This](https://developer.android.com/guide/playcore/in-app-review/kotlin-java#create-reviewmanager) is the Java code showing how to integrate it into your apps.

If not supported currently, what exactly would I have to do in order to port the "In App Review" feature for Android?

Came here from this [StackOverflow question](https://stackoverflow.com/questions/63548518/how-can-i-implement-in-app-reviews-in-xamarin-android) that has been removed now.

**Comment by PatGet** [comment] 2020-08-26 12:01
Hi, the package currently uses core-1.7.2.aar as the Binding Lib. "In App Reviews" needs Version 1.8, at least thats what your linked docs say.
It might work if the aar file is updated, maybe with some changes in the Transforms.
You already know from https://github.com/xamarin/GooglePlayServicesComponents/issues/221 that the PlayCore API has some incompatible APIs but I would expect that the Review Flow should work as it seems that it only displays a new View which lets you rate the app.

**Comment by saamerm** [comment] 2020-09-18 05:39
@PatGet created a PR #4 
Once merged, I will update the example to share the In-App review code.

Please let me know what needs to be done to update the Nuget package. Once that's done I can also share that with the others too! Hopefully we can get a lot more traction on this library :)

**Comment by PatGet** [comment] 2020-09-18 08:12
Nice! I have a local branch where I updated to 1.8 but did not manage to get the rating to work within the 5 minutes I had. Wanted to do that in my current vacation but had not opened the laptop once...
I can merge that and if you update the sample or add a new one to do the rating I can check both features are working and provide a new nuget. Creating/updating the nuget is currently manual process, I hoped to fix that too during my vacation...

**Comment by PatGet** [comment] 2020-09-18 08:20
BTW.: From where did you get the aar file? Would like to ensure that it comes from a trusted source.

**Comment by saamerm** [comment] 2020-09-18 08:22
Sounds like a plan. I got it from here: https://developer.android.com/guide/playcore#native, I just renamed it to add the version number as a suffix

**Comment by saamerm** [comment] 2020-09-18 08:22
@PatGet Sounds like a plan. I got it from here: https://developer.android.com/guide/playcore#native, I just renamed it to add the version number as a suffix

**Comment by PatGet** [comment] 2020-09-18 08:41
Ok, I grabbed it directly from a maven repository so it had the right version already. Did not think about that native zip file to be honest. Great, seems to be fine so I merge.

**Comment by saamerm** [comment] 2020-09-18 15:58
@PatGet #5 is up! 😄

**Comment by AntvissMedia** [comment] 2020-09-18 16:09
@saamerm I had started implementing the same but glad to know someone beat me to it! I will test it tonight and let you know how it goes! Cheers, mate

**Comment by saamerm** [comment] 2020-09-18 16:12
@AntvissMedia no one's getting paid here. I thought no one else cared about it, so I decided to just get it done lol.
How did you find out about this?

**Comment by AntvissMedia** [comment] 2020-09-18 16:22
Same as you probably. Saw the Google post that in-app reviews exist, saw that the xamarin team are not too interested to get this in, found Pat's plugin which takes it "almost" there and then decided to help it get over the edge.

But my time has been limited lately and couldn't focus on it. Got as far as implementing it pretty much like you did, but stopped short of writing a test/example for it.

Speak soon

Kind regards,
Alex

________________________________

**Comment by AntvissMedia** [comment] 2020-09-18 16:22
I'm actually surprised not more people care about it to be honest. It's an awesome feature to have!

Kind regards,
Alex

________________________________

**Comment by AntvissMedia** [comment] 2020-09-19 00:07
![image](https://user-images.githubusercontent.com/48839721/93654174-20837f00-fa14-11ea-98b3-03c2515788e5.png)

I can confirm it works just fine.

The only change I made was to replace the INSTANCE property in MainActivity with the CurrentActivity instance from James Montemagno's plugin. But that's just a preference, not a necessity:

```csharp
       public void ShowPrompt()
        {

#if DEBUG
            var manager = new FakeReviewManager(CrossCurrentActivity.Current.AppContext);
#else         
            var manager = ReviewManagerFactory.Create(CrossCurrentActivity.Current.AppContext);
#endif            
            var request = manager.RequestReviewFlow();
            request.AddOnCompleteListener(new OnCompleteListener(manager));
        }
    }

    public class OnCompleteListener : Java.Lang.Object, IOnCompleteListener
    {
        FakeReviewManager _fakeReviewManager;
        IReviewManager _reviewManager;
        bool _usesFakeManager;
        void IOnCompleteListener.OnComplete(Com.Google.Android.Play.Core.Tasks.Task p0)
        {
            if (p0.IsSuccessful)
            {
                var review = p0.GetResult(Java.Lang.Class.FromType(typeof(ReviewInfo)));
                if (_usesFakeManager)
                {
                    var x = _fakeReviewManager.LaunchReviewFlow(CrossCurrentActivity.Current.Activity, (ReviewInfo)review);
                    x.AddOnCompleteListener(new OnCompleteListener(_fakeReviewManager));
                }
                else
                {
                    var x = _reviewManager.LaunchReviewFlow(CrossCurrentActivity.Current.Activity, (ReviewInfo)review);
                    x.AddOnCompleteListener(new OnCompleteListener(_reviewManager));
                }
            }
        }

```

**Comment by AntvissMedia** [comment] 2020-09-19 00:10
having said that, there is a crash happening when you cancel or select "Not now":

```
JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms)
IReviewManagerInvoker.LaunchReviewFlow (Android.App.Activity p0, Com.Google.Android.Play.Core.Review.ReviewInfo p1)
IOnCompleteListener.OnComplete (Com.Google.Android.Play.Core.Tasks.Task p0)
IOnCompleteListenerInvoker.n_OnComplete_Lcom_google_android_play_core_tasks_Task_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_p0)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.147(intptr,intptr,intptr)
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.PendingIntent com.google.android.play.core.review.ReviewInfo.a()' on a null object reference
com.google.android.play.core.review.c.launchReviewFlow(Unknown Source:9)
crc64f9880a60d3664245.OnCompleteListener.n_onComplete(Native Method)
crc64f9880a60d3664245.OnCompleteListener.onComplete OnCompleteListener.java:44
com.google.android.play.core.tasks.a.run(Unknown Source:23)
android.os.Handler.handleCallback Handler.java:873
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:193
android.app.ActivityThread.main ActivityThread.java:6669
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:493
com.android.internal.os.ZygoteInit.main ZygoteInit.java:858```

**Comment by AntvissMedia** [comment] 2020-09-19 00:28
also, although the popup comes up, the Submit button stays greyed out. Are you seeing the same in your test app?

**Comment by saamerm** [comment] 2020-09-19 02:02
Yes I would also recommend James’s connect instead, but I didn’t want to make it dependency, so I left it out.

**Comment by AntvissMedia** [comment] 2020-09-19 08:46
I've got the app hooked up to App Center for cases like this to make sure nothing gets missed.

Are you seeing the same thing then with your implementation without CurrentActivity (I was thinking that might cause it)?

**Comment by AntvissMedia** [comment] 2020-09-19 09:10
I "fixed" the issue the classic way, with a try-catch around the OnCompleteListener

```csharp
public class OnCompleteListener : Java.Lang.Object, IOnCompleteListener
    {
        IReviewManager _reviewManager;
        private ReviewInfo review;

        void IOnCompleteListener.OnComplete(Task tsk)
        {
            try
            {
                if (tsk.IsSuccessful)
                {
                    review = (ReviewInfo)tsk.GetResult(Java.Lang.Class.FromType(typeof(ReviewInfo)));


                    var x = _reviewManager.LaunchReviewFlow(CrossCurrentActivity.Current.Activity, review);
                    x.AddOnCompleteListener(new OnCompleteListener(_reviewManager));

                }
            }

            catch (Exception ex)
            {
               //Handle Exception
            }
        }

        public OnCompleteListener(IReviewManager reviewManager)
        {
            _reviewManager = reviewManager;
        }
    }
```

Google themselves say that:

> Important: If an error occurs during the in-app review flow, do not inform the user or change your app's normal user flow. Continue your app's normal user flow after onComplete is called.

I have tested the "Not Now" part of it and also the normal workflow by leaving a review and that went through.

**Comment by saamerm** [comment] 2020-09-19 14:46
Yes I just retested it, and you are right. I re-tested and was able to replicate the bug. 
So, I made changes and retested, and the crash went away! Thank you!!

**Comment by saamerm** [comment] 2020-09-21 15:59
@PatGet Any ETA on the nuget package update?

**Comment by PatGet** [comment] 2020-09-21 19:58
@saamerm I just submitted https://www.nuget.org/packages/PlayCore/1.8.0-rc for testing purposes. I decided to go for the same Version Number as the AAR File its based on.

**Comment by saamerm** [comment] 2020-09-21 21:16
Yes. I think that’s the way to go

**Comment by gabrieldwight** [comment] 2020-09-23 09:42
@saamerm, @AntvissMedia  and @PatGet  That is a good progress. Testing the sample now.

**Comment by saamerm** [comment] 2020-09-23 12:37
@PatGet tested the 1.8.0-rc nuget, it looks good and it works 👍

**Comment by PatGet** [comment] 2020-09-23 16:02
I received an update in the morning with an app containing the rc nuget. That worked well and I pushed another update directly to test the immediate update. Hope that will be faster... As soon as I can verify it still works I push a new stsble nuget

**Comment by gabrieldwight** [comment] 2020-09-23 18:26
@PatGet the nuget 1.8.0 rc works well on my side including the play core immediate update. No issues so far.

**Comment by ValonK** [comment] 2020-09-24 09:07
Doesn't work for me tested on multiple devices (Release Mode) nothing happens, am I missing something?

**Comment by AntvissMedia** [comment] 2020-09-24 09:24
@ValonK the nuget is just the Play Core bindings. You need to implement the workflow in your Shared and Android projects. Have a look at the test project for an ideea on how to implement it. 

It also needs to be on a test track not sideloaded. You can use the internal app sharing feature but it will not let you submit the review so you can't test that part.

**Comment by PatGet** [comment] 2020-09-24 20:32
Nuget worked well. Try to create the new stabile Version tomorrow.

**Comment by PatGet** [comment] 2020-09-25 09:12
Stable Version listed on NuGet. Closing the issue.

**Closed by PatGet** 2020-09-25 09:12 UTC

**Comment by pro777s** [comment] 2021-04-02 12:54
> I "fixed" the issue the classic way, with a try-catch around the OnCompleteListener
> 
> 
> > Important: If an error occurs during the in-app review flow, do not inform the user or change your app's normal user flow. Continue your app's normal user flow after onComplete is called.
> 
> I have tested the "Not Now" part of it and also the normal workflow by leaving a review and that went through.

The first answer help me fix bug: https://stackoverflow.com/questions/63552588/android-in-app-review-pop-up-crashes-the-app.
